const loginEndPoint = 'login';
const homeEndPoint = 'home';
const categoryEndPoint = 'categories';
const changeFavoriteEndPoint = 'favorites';
const favoriteEndPoint = 'favorites';
const profileEndPoint = 'profile';
const updateProfileEndPoint = 'update-profile';
const registerEndPoint = 'register';
String productDetailsEndPoint (int id)=> 'products/$id';
late String language;
String? token='';